#TOMCAT SERVER
server:
  port: 8080

#JPA
spring:
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect

#Datasource
  datasource:
    url: jdbc:mysql://localhost:8889/cicet612?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
